language: cpp
cache: ccache
sudo: required
dist: trusty
os:
  - linux
env:
  global:
  - LANG="en_US.UTF-8"
compiler:
  - gcc


install:
  - sudo apt-get install nvidia-cuda-toolkit
  - wget https://developer.download.nvidia.com/compute/cuda/9.2/secure/Prod/local_installers/cuda-repo-ubuntu1604-9-2-local_9.2.88-1_amd64.deb?CtL1_E26Pi2VigBxVhj6ZuQ4wRjfPLLyONZmAHfBDuCfAfE2gPOQ8DsIntcLrii-0EHZ-ZJPyGoZWzg-dfmFfEjH5qXASmR3JZJ3vl1KFlSnIc-8O_xs2q11LAa-dmoRSpwI8domlUUqQAlEoAtK0_FHUGA9OFmzw5ve_ifYYKTT5gEijRfhbyNKbDsThPfWC6WXAeSmrZNpo00_Os0
script:

  - PATH=/usr/local/bin:$PATH
  - nvcc --version
  - cd tools
  - bash gpu_build.sh
    #bash anakin_docker_build_and_run.sh -p NVIDIA-GPU -o Centos -m Build

branches:
  only:
  - master
  - developing

notifications:
  email:
    recipients:
    - xukailu@baidu.com
    on_success: change
    on_failure: always

